parameters:
#    clean_water_map.example.class: CleanWater\MapBundle\Example

services:
#    clean_water_map.example:
#        class: %clean_water_map.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
