<?php

namespace CleanWater\MapBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class MapController__JMSInjector
{
    public static function inject($container) {
        $instance = new \CleanWater\MapBundle\Controller\MapController();
        return $instance;
    }
}
